[mgr]
prepend_keymap = [
  { on = ".", run = "hidden toggle", desc = "Toggle hidden files" },
  { on = ["g", "s"], run = "cd ~/.ssh", desc = "SSH config" },
  { on = ["g", "x"], run = 'shell -- ya emit cd "$(git -C "$(dirname "$(readlink -f "$HOME/.config/yazi/yazi.toml")")" rev-parse --show-toplevel)"', desc = "Dotfiles checkout" },
  { on = ["g", "d"], run = 'cd ~/Downloads/', desc = "Downloads" },
  { on = ["g", "r"], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"', desc = "Git root" },
  { on = ["g", "u"], run = 'cd ~/Development/', desc = "Development" },
  { on = ["g", "y"], run = "cd ~/.config/yazi", desc = "Yazi config" },
  { on = ["g", "l"], run = "shell --block -- lazygit", desc = "LazyGit" },
  { on = ["g", "w"], run = "plugin vcs-files", desc = "Git changes" },
  { on = ["c", "m"], run = "plugin chmod", desc = "Change permissions" },
  { on = ["T", "p"], run = "plugin toggle-pane min-preview", desc = "Toggle preview" },
  { on = ["T", "f"], run = "plugin toggle-pane max-preview", desc = "Maximize preview" },
  { on = "<C-d>", run = "seek 5", desc = "Preview down" },
  { on = "<C-u>", run = "seek -5", desc = "Preview up" },
  { on = "+", run = "plugin zoom 1", desc = "Zoom in" },
  { on = "-", run = "plugin zoom -1", desc = "Zoom out" },
  { on = "1", run = "plugin relative-motions 1", desc = "Relative motion" },
  { on = "2", run = "plugin relative-motions 2", desc = "Relative motion" },
  { on = "3", run = "plugin relative-motions 3", desc = "Relative motion" },
  { on = "4", run = "plugin relative-motions 4", desc = "Relative motion" },
  { on = "5", run = "plugin relative-motions 5", desc = "Relative motion" },
  { on = "6", run = "plugin relative-motions 6", desc = "Relative motion" },
  { on = "7", run = "plugin relative-motions 7", desc = "Relative motion" },
  { on = "8", run = "plugin relative-motions 8", desc = "Relative motion" },
  { on = "9", run = "plugin relative-motions 9", desc = "Relative motion" },
]
